// generate_teapot.js - one-shot Node script that writes a low-poly torus to
// teapot.obj as a placeholder OBJ (no real Utah teapot was on disk). It emits
// triangulated faces in `v//vn` format with explicit vertex normals, matching
// what Model.js / the Lab 3 parser expects. Drop in a real teapot.obj anytime;
// the loader handles any triangulated v//vn OBJ. Grader does not need to run this.

const fs = require('fs');

const R = 1.0;          // major radius (center of tube to center of torus)
const r = 0.4;          // minor radius (tube thickness)
const MAJOR = 32;       // segments around the big ring
const MINOR = 16;       // segments around the tube

const positions = [];
const normals = [];

for (let i = 0; i < MAJOR; i++) {
  const u = (i / MAJOR) * 2 * Math.PI;
  const cu = Math.cos(u), su = Math.sin(u);
  for (let j = 0; j < MINOR; j++) {
    const v = (j / MINOR) * 2 * Math.PI;
    const cv = Math.cos(v), sv = Math.sin(v);

    // surface point
    const x = (R + r * cv) * cu;
    const y = r * sv;
    const z = (R + r * cv) * su;
    positions.push([x, y, z]);

    // outward normal (already unit length)
    normals.push([cv * cu, sv, cv * su]);
  }
}

const idx = (i, j) => (i % MAJOR) * MINOR + (j % MINOR) + 1;  // 1-based OBJ index

let out = '# Low-poly torus placeholder generated by generate_teapot.js\n';
out += `# major=${MAJOR} minor=${MINOR} R=${R} r=${r}\n`;
out += 'o Torus\n';

for (const [x, y, z] of positions) {
  out += `v ${x.toFixed(6)} ${y.toFixed(6)} ${z.toFixed(6)}\n`;
}
for (const [nx, ny, nz] of normals) {
  out += `vn ${nx.toFixed(6)} ${ny.toFixed(6)} ${nz.toFixed(6)}\n`;
}

for (let i = 0; i < MAJOR; i++) {
  for (let j = 0; j < MINOR; j++) {
    const a = idx(i, j);
    const b = idx(i + 1, j);
    const c = idx(i + 1, j + 1);
    const d = idx(i, j + 1);
    // two triangles per quad; position index == normal index for each vertex
    out += `f ${a}//${a} ${b}//${b} ${c}//${c}\n`;
    out += `f ${a}//${a} ${c}//${c} ${d}//${d}\n`;
  }
}

fs.writeFileSync(__dirname + '/teapot.obj', out);
console.log('Wrote teapot.obj:', positions.length, 'verts,', MAJOR * MINOR * 2, 'tris');
